export const articles: any = {
  politics: [
    {
      url: "/our_work/our_categories/politics/MauritiusPresidentialElections2024.html",
      cardTitle:
        "Democratic Dynamics: Mauritius' 2024 Presidential Elections Explained",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/Cover-3.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/indianAllianceProspectsInUP.html",
      cardTitle: "INDIA Alliance Prospects In Uttar Pradesh",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/INDIA ALLIANCE PROSPECTS IN UTTAR PRADESH.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/RiseOf_APP_In_India.html",
      cardTitle: "Rise of AAP in India",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/AAM-AADMI-Party.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/IndianAllianceAndBihar.html",
      cardTitle: "Electoral Dynamics: A look at Bihar’s Political Landscape",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/India Alliance and Bihar.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/RamMandirAndElections.html",
      cardTitle: "Ram Mandir and General Elections 2024",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/Ram-Mandir-Creative -3-01.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/decodingDomesticMandateTg.html",
      cardTitle:
        "Resurgent Congress's Historic Win in Telangana's 2023 Assembly Elections: A Deep Dive into Dynamics and Margins",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/decodingDomesticMandateTg.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/decodingDomesticMandateMp.html",
      cardTitle:
        "BJP Roars to Victory in Madhya Pradesh Elections: Ladli Behna Scheme and PM Modi's Leadership Seal the Deal",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/decodingDomesticMandateMp.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/decodingDomesticMandateRj.html",
      cardTitle:
        " BJP's Resounding Victory in Rajasthan Elections: Unpacking the Dynamics, Decoding Margins",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/decodingDomesticMandateRj.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/decodingDomesticMandateCg.html",
      cardTitle:
        "BJP's Impressive Victory: Deciphering the Patterns and Margins in Chhattisgarh Assembly Elections 2023",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/decodingDomesticMandateCg.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/scindiaFactor.html",
      cardTitle:
        "The Scindia Factor Jyotiraditya Scindia's Influence on Madhya Pradesh Politics",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/scindia.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/RjCandidate.html",
      cardTitle:
        "Will category and caste wise ticket distribution matter in Rajasthan Assembly Election 2023?",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/rj_candidate.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/welfareCh.html",
      cardTitle:
        " Election Alchemy: Can Welfare Schemes Propel Congress's Comeback Bid in Chhattisgarh?",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/welfareCh.jpg",
      cardVideo: "",
    },

    {
      url: "/our_work/our_categories/politics/howTelnaganaVoted.html",
      cardTitle: "How Telangana Voted in Its First Election",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/how-tl-voted.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/howRajasthanVoted.html",
      cardTitle: "How Rajasthan Voted in its First Election",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/how-rajasthan-voted.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/tribalVote.html",
      cardTitle:
        "The Tribal Vote: Indigenous Communities and Their Impact on the 2023 Chattisgarh Assembly Elections",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/siddi-tribe.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/welfareTL.html",
      cardTitle:
        " Election Alchemy: Can Welfare Schemes Propel BRS's Comeback Bid in Telangana?",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/welfareTL.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/CgMp.html",
      cardTitle:
        " A Comparison of political landscape 1998 Madhya Pradesh Unified and 2003 Post Chhattisgarh Separation",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/CgMp.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/VotesThatMatterCh.html",
      cardTitle:
        "Votes that Matter: A Deep Dive into the Impact of Voter Turnout and NOTA in past Chhattisgarh Assembly Elections",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/VotesThatMatterCh.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/electionAlchemyWelfare.html",
      cardTitle:
        "Election Alchemy: Can Welfare Schemes Propel Congress's Comeback Bid in Rajasthan?",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/electionAlchemyWelfare.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/TlCountdown2023.html",
      cardTitle:
        "Countdown to the 2023 Telangana Assembly Election: Strategies and Rallies",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/tl_countdown.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/ChCountdown2023.html",
      cardTitle:
        "Countdown to the 2023 Chhattisgarh Assembly Election: Strategies and Rallies",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/ch_countdown.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/RjCountdown2023.html",
      cardTitle:
        "Countdown to the 2023 Rajasthan Assembly Election: Strategies and Rallies",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/rj_countdown.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/MpCountdown2023.html",
      cardTitle:
        "Countdown to the 2023 Madhya Pradesh Assembly Election Strategies and Rallies",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/mp_countdown.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/ElelctionAlechemy.html",
      cardTitle:
        "Election Alchemy: Will Ladli Behna be a game-changer in the upcoming MP elections?",
      articleCategory: "politics",
      articleType: "Blog",
      cardImage: "/images/posts/electionAlchemy.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/BypollSept2023ExitPoll.html",
      cardTitle: "Bypoll Sept 2023: Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/sept-bypoll1.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/PollsterRanking2022.html",
      cardTitle: "Pollster Ranking 2022",
      articleCategory: "politics",
      articleType: "Article",
      cardImage: "/images/posts/PollsterRanking2022.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/Tripura2023ExitPoll.html",
      cardTitle: "Tripura 2023 Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Tripura2023ExitPoll.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/Bypoll2023ExitPoll.html",
      cardTitle: "Bypoll 2023 Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Bypoll2023ExitPoll.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/politics/TripuraAssemblyElections2023.html",
      cardTitle: "Tripura Assembly Elections 2023",
      articleCategory: "politics",
      articleType: "Video",
      cardImage: "",
      cardVideo: "Zfi7dqlTm-c",
    },
    {
      url: "/our_work/our_categories/politics/NationalVotersDay.html",
      cardTitle: "National Voters Day",
      articleCategory: "politics",
      articleType: "Video",
      cardImage: "",
      cardVideo: "jRHEr5tM3yQ",
    },
    {
      url: "/our_work/our_categories/promo/most_accurate_prediction_gujarat_2022.html",
      cardTitle: "Most Accurate Prediction Gujarat 2022 Assembly Election",
      articleCategory: "politics",
      articleType: "Video",
      cardImage: "",
      cardVideo: "ztDsb47wGF4",
    },
    {
      url: "/our_work/our_categories/promo/gujarat_2022_prediction.html",
      cardTitle: "Gujarat 2022 Election Prediction",
      articleCategory: "politics",
      articleType: "Video",
      cardImage: "",
      cardVideo: "mSTKxEInmLQ",
    },
    {
      url: "/our_work/our_categories/assembly_election/gujarat_2022_predictionPost.html",
      cardTitle: "Gujarat 2022 Assembly Election Prediction",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/gujarat_2022_predictionPost.jpg",
      cardVideo: "",
    },

    {
      url: "/our_work/our_categories/assembly_election/2022_election_gujrat_exit_poll.html",
      cardTitle: "2022 Assembly Election Gujarat Exit Poll",
      articleCategory: "politics",
      articleType: "Video",
      cardImage: "",
      cardVideo: "mJm4GqLweTI",
    },
    {
      url: "/our_work/our_categories/assembly_election/2022_gujrat_vote_share.html",
      cardTitle: "2022 Gujarat Assembly Election Vote Share",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/2022_gujrat_vote_share.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/assembly_election/2022_gujrat_seat_prediction.html",
      cardTitle: "2022 Gujarat Assembly Election Seat Prediction",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/2022_gujrat_vote_prediction.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/khatauliBypollPost.html",
      cardTitle: "Khatauli By-Poll Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Exit Poll Khatauli_Bypoll.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/kurhaniBypollPost.html",
      cardTitle: "Kurhani By-Poll Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Exit Poll Kurhani_Bypoll.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/mainpuriBypollPost.html",
      cardTitle: "Mainpuri By-Poll Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Exit Poll Mainpuri Bypoll.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/rampurBypoll.html",
      cardTitle: "Rampur By-Poll Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Exit Poll Rampur Bypoll.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/sardarshaharBypoll.html",
      cardTitle: "Sardarshahar By-Poll Exit Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Exit Poll Sardarshahar_Bypoll.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/mokamaPost.html",
      cardTitle: "Mokama By-Poll Opinion Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Opinion poll_Mokama_Bypoll_2022.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/gopalganjPost.html",
      cardTitle: "Gopalganj By-Poll Opinion Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Opinionpoll_Gopalganj_bypoll_2022.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/bye_election/munugodePost.html",
      cardTitle: "Munugode By-Poll Opinion Poll",
      articleCategory: "politics",
      articleType: "Post",
      cardImage: "/images/posts/Opinionpoll_Munugode_bypoll_2022.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/assembly_election/pollster_ranking.html",
      cardTitle: "Dhruv Research Pollster Ranking 2020",
      articleCategory: "politics",
      articleType: "Article",
      cardImage: "/images/posts/IMG-20210127-WA0017.jpg",
      cardVideo: "",
    },
  ],
  economy: [
    {
      url: "/our_work/our_categories/economy/economicResilienceIndia.html",
      cardTitle: "Economic Resilience in India: The Public's Perspective",
      articleCategory: "economy",
      articleType: "Blog",
      cardImage: "/images/posts/economicResilienceIndia.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/economy/budget2023.html",
      cardTitle: "Budget 2023-2024",
      articleCategory: "economy",
      articleType: "Video",
      cardImage: "",
      cardVideo: "CAD2SkbY3zc",
    },
    {
      url: "/our_work/our_categories/economy/surveyPost.html",
      cardTitle: "We surveyed 25,000+ Indians",
      articleCategory: "economy",
      articleType: "Post",
      cardImage: "/images/posts/post-1.jpg",
      cardVideo: "",
    },
  ],

  sports: [
    {
      url: "/our_work/our_categories/sports/ipl2023.html",
      cardTitle: "IPL 2023",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/ipl2023.png",
      cardVideo: "",
    },

    {
      url: "/our_work/our_categories/sports/WPLAuction2023Overall.html",
      cardTitle: "WPL Auction 2023 Overall",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/WPL2023_Auction_1.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/sports/WPLAuction2023Batter.html",
      cardTitle: "WPL Auction 2023 Batter",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/WPL2023_Auction_2.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/sports/WPLAuction2023Bowler.html",
      cardTitle: "WPL Auction 2023 Bowler",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/WPL 2023 Auction 3.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/sports/ipl2023Post.html",
      cardTitle: "IPL 2023 Auction",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/ipl.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/sports/fifa2022Post.html",
      cardTitle: "Most Successful Clubs : FIFA WORLD CUP 2022",
      articleCategory: "sports",
      articleType: "Post",
      cardImage: "/images/posts/fifa2022.png",
      cardVideo: "",
    },
  ],

  entertainment: [
    {
      url: "/our_work/our_categories/entertainment/dreamRatingOTT2023.html",
      cardTitle: "Dream Rating OTT Overall Year End Article 2023",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage:
        "/images/posts/Viewer’s Choice - OTT Landscape in India-01.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/EvolutionOfHipHop.html",
      cardTitle: "The Evolution of Hip Hop in India: From Streets to Screens",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage: "/images/posts/Hip Hop Articles.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/explore_consumer_mind.html",
      cardTitle:
        "Exploring Consumer minds with year end analysis from Brand Preference Index",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage: "/images/posts/CPI Year End Header Image.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/explore_entrainment.html",
      cardTitle: "The Dynamic World of Entertainment: A Closer Look",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage: "/images/posts/explore-entertainment.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/BrandPreferenceIndex.html",
      cardTitle: "Brand Preference Index: June 2023",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage: "/images/posts/cpi.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/ottCollated.html",
      cardTitle: "Viewer's Choice: OTT Landscape in India",
      articleCategory: "entertainment",
      articleType: "Blog",
      cardImage: "/images/posts/ottcollated.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/dreamratingv2.html",
      cardTitle: "Dream Rating V 2.0",
      articleCategory: "entertainment",
      articleType: "Post",
      cardImage: "/images/posts/Dream RatingV2.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/DREAMRating.html",
      cardTitle: "DREAM Rating",
      articleCategory: "entertainment",
      articleType: "Article",
      cardImage: "/images/posts/DREAMRating.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/dreamRatingOTT.html",
      cardTitle: "DREAM Rating OTT",
      articleCategory: "entertainment",
      articleType: "Post",
      cardImage: "/images/posts/dreamRatingOTT.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/dreamRatingGenre.html",
      cardTitle: "DREAM Rating Genre",
      articleCategory: "entertainment",
      articleType: "Post",
      cardImage: "/images/posts/dreamRatingGenre.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/entertainment/brandReportCard.html",
      cardTitle: "Brand Report Card 2022",
      articleCategory: "entertainment",
      articleType: "Post",
      cardImage: "/images/posts/brandReport.png",
      cardVideo: "",
    },
  ],
  didyouknow: [
    {
      url: "/our_work/our_categories/didyouknow/InternationalDayForests.html",
      cardTitle: "International Day of Forests",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/InternationalDayForests.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/WorldWaterDay.html",
      cardTitle: "World Water Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/WorldWaterDay.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/GlobalRecyclingDay.html",
      cardTitle: "Global Recycling Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/GlobalRecyclingDay.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/WorldJustice.html",
      cardTitle: "World Justice",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/WorldJusticeTitle.jpg.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/worldWildlifeDay.html",
      cardTitle: "World Wildlife Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/worldWildlifeDay.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/ukraineRussiaConflict.html",
      cardTitle: "Ukraine Russia Conflict",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/ukraineRussiaConflict.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/internationalWomansDay2023.html",
      cardTitle: "International Womans's Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/internationalWomansDay2023.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/chatGPT.html",
      cardTitle: "ChatGPT",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/chatgptVSbard.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/InternationalMotherLaguageDay.html",
      cardTitle: "International Mother Language Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/international mother language.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/WorldSocialJusticeDay.html",
      cardTitle: "World Social Justice Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/socialjusticeday.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/WomeninStem.html",
      cardTitle: "Women in STEM",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/women stem.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/ValentinesDay.html",
      cardTitle: "Valentine's Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/valentines dat.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/IndianArmyDay.html",
      cardTitle: "Indian Army Day",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/indian army day.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/didyouknow/didyouknowPost.html",
      cardTitle: "Did You Know!",
      articleCategory: "didyouknow",
      articleType: "Post",
      cardImage: "/images/posts/users_post.jpg",
      cardVideo: "",
    },
  ],
  governance: [
    {
      url: "/our_work/our_categories/governance/investmentsInIndia.html",
      cardTitle: "Investments in India",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/FDI Inflows.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/G20AndBrics.html",
      cardTitle: "India's global standing with a focus on BRICS and G20",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/G20 & Brics.jpeg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/indianUPI.html",
      cardTitle: "India's UPI's Ascent on the International Stage",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/UPI.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/uniformCivilCode.html",
      cardTitle:
        "Will Uniform Civil Code define the narrative for 2024 elections?",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/UCC.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/chandrayaan3.html",
      cardTitle:
        "Chandrayaan 3: A Catalyst for India's Space Exploration Reputation",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/chandrayaan.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/IndianPoliticalSabhas.html",
      cardTitle:
        "Indian Political Sabhas: Platforms of Discourse and Democracy",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/india_political_sabhas.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/DecodingVotingBehaviour.html",
      cardTitle:
        " Voting Behaviour: Understanding Factors Influencing Voter Choice in India",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/India_Gujarat_Election_09420.jpg",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/GenerativeAI.html",
      cardTitle:
        "The Promise of Generative AI in India and the Need for Responsible Governance",
      articleCategory: "governance",
      articleType: "Blog",
      cardImage: "/images/posts/AI.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/healingthenation.html",
      cardTitle: "PM-JAY: Healing the Nation",
      articleCategory: "governance",
      articleType: "Article",
      cardImage: "/images/posts/HealingtheNation.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/delhiwatersurvey.html",
      cardTitle: "Delhi Water Survey",
      articleCategory: "governance",
      articleType: "Post",
      cardImage: "/images/posts/delhiwatersupply.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/G20AgriculturalDevelopmentMeeting.html",
      cardTitle:
        " G20 Agricultural Development Meeting to Secure Global Food Supply",
      articleCategory: "governance",
      articleType: "Article",
      cardImage: "/images/posts/G20AgriculturalDevelopmentMeeting.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/G20TradeandInvestmentWorkingGroup.html",
      cardTitle: "G20 Trade and Investment Working Group",
      articleCategory: "governance",
      articleType: "Article",
      cardImage: "/images/posts/G20TradeandInvestmentWorkingGroup.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/G20EducationWorkingGroup.html",
      cardTitle: "G20 Education Working Group",
      articleCategory: "governance",
      articleType: "Article",
      cardImage: "/images/posts/G20EducationWorkingGroup.png",
      cardVideo: "",
    },
    {
      url: "/our_work/our_categories/governance/G20FinancialInclusion.html",
      cardTitle: "G20 Financial Inclusion",
      articleCategory: "governance",
      articleType: "Article",
      cardImage: "/images/posts/g20post.png",
      cardVideo: "",
    },
  ],
};
